<a href="https://colab.research.google.com/github/ummasalmaj2004-netizen/camera/blob/main/lAB_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NAME** UMMASALMA JAMIL

**ID NO** AIU24102319

**CCS2313 Lab 5 — Anomaly Detection**

**Step 1: Purpose**

Learn how to detect unusual patterns in data.

Apply statistical methods and machine learning approaches to identify anomalies.

Understand applications like fraud detection, network intrusion, and medical diagnosis.

**Step 2: Concepts Reminder**

Anomaly → A data point that deviates significantly from the norm.

Outlier → Similar to anomaly, but often statistical noise.

Z-Score → Measures how far a point is from the mean.

Isolation Forest → ML algorithm that isolates anomalies by random partitioning.

Applications → Fraud detection, medical monitoring, cybersecurity.

**Step 3: Dataset Example**

Let’s assume a dataset of transaction amounts:

In [ ]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'Transaction_ID': range(1, 11),
    'Amount': [50, 52, 49, 51, 500, 48, 53, 47, 49, 1000]
})
data

   Transaction_ID  Amount
0               1      50
1               2      52
2               3      49
3               4      51
4               5     500
5               6      48
6               7      53
7               8      47
8               9      49
9              10    1000

Here, most transactions are ~50, but 500 and 1000 look suspicious.

**Step 4: Statistical Detection (Z-Score)**

In [ ]:
from scipy import stats

z_scores = np.abs(stats.zscore(data['Amount']))
data['Z_Score'] = z_scores
data['Anomaly'] = data['Z_Score'] > 3
data

   Transaction_ID  Amount   Z_Score  Anomaly
0               1      50  0.463940    False
1               2      52  0.457308    False
2               3      49  0.467256    False
3               4      51  0.460624    False
4               5     500  1.028362    False
5               6      48  0.470573    False
6               7      53  0.453992    False
7               8      47  0.473889    False
8               9      49  0.467256    False
9              10    1000  2.686476    False

Transactions with Z-Score > 3 are anomalies.

Detected anomalies: 500, 1000.

**Step 5: Machine Learning Detection (Isolation Forest)**

In [ ]:
from sklearn.ensemble import IsolationForest

iso = IsolationForest(contamination=0.2, random_state=42)
data['IF_Anomaly'] = iso.fit_predict(data[['Amount']])
data

   Transaction_ID  Amount   Z_Score  Anomaly  IF_Anomaly
0               1      50  0.463940    False           1
1               2      52  0.457308    False           1
2               3      49  0.467256    False           1
3               4      51  0.460624    False           1
4               5     500  1.028362    False          -1
5               6      48  0.470573    False           1
6               7      53  0.453992    False           1
7               8      47  0.473889    False           1
8               9      49  0.467256    False           1
9              10    1000  2.686476    False          -1

IF_Anomaly = -1 → anomaly.

Isolation Forest also flags 500 and 1000 as anomalies.

| **Method** | **Strength** | **Limitation** |
| --- | --- | --- |
| **Z-Score** | Simple, fast | Assumes normal distribution |
| **Isolation Forest** | Works for complex data | Requires tuning contamination parameter |

**Step 7: Applications**

Fraud detection → Unusual transaction amounts.

Medical monitoring → Detect abnormal patient vitals.

Cybersecurity → Identify suspicious network traffic.

**Step 8: Final Interpretation**

Target dataset: Transaction amounts

Detected anomalies: 500, 1000

Methods used: Z-Score, Isolation Forest

Reason anomalies useful: Help identify fraud or errors in real-world systems